### ISSUE TITLE
How should the endpoints be constructed

### ISSUE THREAD

**Issue by ekeeya** [glific/floweditor#45]
Hello,
I am in a desperate need to use this package due to its awesomeness.
But my knowledge is still limited regarding the code base of this project .
I have however managed to identify a way to use it but am not quite sure.

in index.html they is a js config object that i guess tells the flow editor on which backend API to use and respective endpoints.
I have managed to create thes end-points uding djngo-restframework but i still can not get the flow-editor running. Currently I get error 
```TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at i (createForOfIteratorHelper.js:3)
    at thunks.ts:298
    at index.js:11
    at dispatch (applyMiddleware.js:35)
    at thunks.ts:405
(anonymous) @ thunks.ts:423
Promise.catch (async)
(anonymous) @ thunks.ts:419
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ thunks.ts:377
(anonymous) @ index.js:11
(anonymous) @ bindActionCreators.js:3
value @ index.tsx:115
os @ react-dom.production.min.js:212
pu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Bi @ react-dom.production.min.js:122
du @ react-dom.production.min.js:248
Js @ react-dom.production.min.js:239
$s @ react-dom.production.min.js:230
Nu @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tu @ react-dom.production.min.js:240
Bu @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
window.showFlowEditor @ index.js:26
(anonymous) @ flow-editor:147```


I suspect the issue to be coming from the /revisions end-point therefore I am requesting for assistance on how best I can make my end-points, i.e which methods they expect and which responses they should return for each endpoint.

You assistance will be greatly appreciated. 
Thank you.

**Comment by mdshamoon** [comment]
Hello @ekeeya we also took some time to construct these endpoints and I think we have documented some part of it. Let me check with my team if we can help you with it. 

This is a forked version of the original flow editor used in RapidPro. We have updated it with some changes needed specifically in Glific. So you may want to use the original version.

Also, could I know where are you going to use this package? Since if you want to work with flow editor you can easily clone RapidPro or Glific which are both open source.

**Comment by ekeeya** [comment]
Hello @mdshamoon ,I have worked with RapidPro before but I had decided to not put the issue on the main repo at @nyaruka and noticed you seem to have implemented it in a project outside RapidPro eco-system which is my major objective.

I have an application already in production but I would wish to add a messaging component that uses this flow logic similar to the one in RapidPro.
I will gladly wait for your kind assistance.
Thank you.

**Comment by mdshamoon** [comment]
@ekeeya we have documented our understanding in these docs https://glific.github.io/glific/doc/GlificWeb.Flows.FlowEditorController.html but they are in Elixir. If you want any further details and understanding of these we can get on a call and discuss further. Also, we can guide you in the whole process so you don't make mistakes that we did :)

**Comment by ekeeya** [comment]
@mdshamoon, I honestly had not heard of Elixir before, but am really exited for the guidance, I for one am using django-restframework (python) for developing the end points.

It would be so helpful and deeply appreciated if you guys can offer me a deeper insight. 
I will patiently be waiting for when you have time at your convenience and probably jump onto a call.
Meanwhile, I'll be examining  the resources you have provided.

**Comment by dlobo** [comment]
@ekeeya your best bet is to look at the code here:

https://github.com/glific/glific/blob/master/lib/glific_web/flows/flow_editor_controller.ex

the language does not make a difference and we have just implemented functions that return the json as expected by flow editor

You can check this directory:

https://github.com/nyaruka/floweditor/tree/main/src/test/assets

to see the json format that flow editor requires

and this file to see how we set the config

https://github.com/glific/glific-frontend/blob/master/src/components/floweditor/FlowEditor.tsx

You can ping us on our discord channel if you have any questions:

https://discord.gg/me6NCMu

**Comment by ekeeya** [comment]
@dlobo, thank you very much.
With guidance from your resources, I have managed to finally set it up.
I am so grateful for your kind assistance.
Thank you very much.
